name: 🚀 Deploy website on push

on: workflow_dispatch

jobs:
  web-deploy:
    name: 🎉 Deploy
    runs-on: ubuntu-latest
    steps:

    - name: 🚚 Get latest code
      uses: actions/checkout@v2.3.2
    
    - name: 📂 Sync files
      uses: SamKirkland/FTP-Deploy-Action@4.0.0
      with:
        server: a2ebb.netcup.net
        username: ${{ secrets.ftp_user }}
        password: ${{ secrets.ftp_pass }}
